#sql/reset.sql
  
DROP TABLE KB_KEYWORD CASCADE CONSTRAINTS;
DROP TABLE KNOWLEDGE_BASE_ARTICLE CASCADE CONSTRAINTS;
DROP TABLE TICKET_STATUS_HISTORY CASCADE CONSTRAINTS;
DROP TABLE TICKET_COMMENT CASCADE CONSTRAINTS;
DROP TABLE TICKET CASCADE CONSTRAINTS;

-- Lookup tables
DROP TABLE STATUS CASCADE CONSTRAINTS;
DROP TABLE PRIORITY CASCADE CONSTRAINTS;

-- User + Company
DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE COMPANY CASCADE CONSTRAINTS;

-- Category tables
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE SUBCATEGORY CASCADE CONSTRAINTS;
