Company 
CREATE TABLE COMPANY (
    COMPANY_ID   NUMBER        NOT NULL,
    NAME         VARCHAR2(100) NOT NULL,
    DOMAIN       VARCHAR2(100),
    STATUS       VARCHAR2(20)  DEFAULT 'ACTIVE',
    CREATED_AT   DATE          DEFAULT SYSDATE,
    CONSTRAINT PK_COMPANY PRIMARY KEY (COMPANY_ID)
);



CREATE TABLE USER_ACCOUNT (
    USER_ID     NUMBER          NOT NULL,
    COMPANY_ID  NUMBER,
    NAME        VARCHAR2(120)   NOT NULL,
    CONTACT     VARCHAR2(200),
    ROLE        VARCHAR2(30),
    CREATED_AT  DATE            DEFAULT SYSDATE,
    ASSIGNED_TO NUMBER,
    CONSTRAINT PK_USER_ACCOUNT PRIMARY KEY (USER_ID)
    CONSTRAINT fk_user_company
        FOREIGN KEY (company_id)
        REFERENCES COMPANY(company_id)
);

CREATE TABLE PRIORITY (
    PRIORITY_ID  NUMBER          NOT NULL,
    NAME         VARCHAR2(50)    NOT NULL,
    SORT_ORDER   NUMBER,
    SLA_HOURS    NUMBER,
    CONSTRAINT PK_PRIORITY PRIMARY KEY (PRIORITY_ID)
);


CREATE TABLE STATUS (
    STATUS_ID     NUMBER          NOT NULL,
    STATUS_NAME   VARCHAR2(50)    NOT NULL,
    DESCRIPTION   VARCHAR2(200),
    IS_CLOSED     CHAR(1)         DEFAULT 'N',
    CONSTRAINT PK_STATUS PRIMARY KEY (STATUS_ID)
);


CREATE TABLE CATEGORY (
    category_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name   VARCHAR2(150) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE SUBCATEGORY (
    subcategory_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_id       NUMBER NOT NULL,
    subcategory_name  VARCHAR2(150) NOT NULL,

    CONSTRAINT pk_subcategory PRIMARY KEY (subcategory_id),

    CONSTRAINT fk_subcategory_category
        FOREIGN KEY (category_id)
        REFERENCES CATEGORY(category_id)
        ON DELETE CASCADE
);

CREATE TABLE TICKET (
    ticket_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    company_id      NUMBER NOT NULL,
    title           VARCHAR2(200) NOT NULL,
    status_id       NUMBER NOT NULL,
    created_date    DATE DEFAULT SYSDATE,
    created_by      NUMBER NOT NULL,
    assigned_to     NUMBER,
    priority_id     NUMBER NOT NULL,
    subcategory_id  NUMBER,
    subject         VARCHAR2(200),
    description     CLOB,
    sla_due_At         DATE,

    CONSTRAINT pk_ticket PRIMARY KEY (ticket_id),

    -- Foreign Keys
    CONSTRAINT fk_ticket_company
        FOREIGN KEY (company_id)
        REFERENCES COMPANY(company_id),

    CONSTRAINT fk_ticket_status
        FOREIGN KEY (status_id)
        REFERENCES STATUS(status_id),

    CONSTRAINT fk_ticket_priority
        FOREIGN KEY (priority_id)
        REFERENCES PRIORITY(priority_id),

    CONSTRAINT fk_ticket_subcategory
        FOREIGN KEY (subcategory_id)
        REFERENCES SUBCATEGORY(subcategory_id),

    CONSTRAINT fk_ticket_created_by
        FOREIGN KEY (created_by)
        REFERENCES USER_ACCOUNT(user_id),

    CONSTRAINT fk_ticket_assigned_to
        FOREIGN KEY (assigned_to)
        REFERENCES USER_ACCOUNT(user_id)
);

CREATE TABLE TICKET_COMMENT (
    comment_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ticket_id     NUMBER NOT NULL,
    user_id       NUMBER NOT NULL,
    comment_text  CLOB,

    CONSTRAINT pk_ticket_comment PRIMARY KEY (comment_id),

    CONSTRAINT fk_comment_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES TICKET(ticket_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_comment_user
        FOREIGN KEY (user_id)
        REFERENCES USER_ACCOUNT(user_id)
);

CREATE TABLE TICKET_STATUS_HISTORY (
    TICKET_STATUS_HISTORY_ID  NUMBER          NOT NULL,
    TICKET_ID                 NUMBER          NOT NULL,
    FROM_STATUS_ID            NUMBER,
    TO_STATUS_ID              NUMBER          NOT NULL,
    CHANGE_BY                 NUMBER,
    CHANGE_DATE               DATE             DEFAULT SYSDATE,
    
    CONSTRAINT PK_TICKET_STATUS_HISTORY 
        PRIMARY KEY (TICKET_STATUS_HISTORY_ID)
);


ALTER TABLE TICKET_STATUS_HISTORY
ADD CONSTRAINT FK_TSH_TICKET
FOREIGN KEY (TICKET_ID)
REFERENCES TICKET (TICKET_ID);

ALTER TABLE TICKET_STATUS_HISTORY
ADD CONSTRAINT FK_TSH_FROM_STATUS
FOREIGN KEY (FROM_STATUS_ID)
REFERENCES STATUS (STATUS_ID);

ALTER TABLE TICKET_STATUS_HISTORY
ADD CONSTRAINT FK_TSH_TO_STATUS
FOREIGN KEY (TO_STATUS_ID)
REFERENCES STATUS (STATUS_ID);

ALTER TABLE TICKET_STATUS_HISTORY
ADD CONSTRAINT FK_TSH_CHANGE_BY
FOREIGN KEY (CHANGE_BY)
REFERENCES USER_ACCOUNT (USER_ID);


CREATE TABLE KNOWLEDGE_BASE_ARTICLE (
    article_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title         VARCHAR2(200) NOT NULL,
    content       CLOB NOT NULL,
    created_at    DATE DEFAULT SYSDATE,

    CONSTRAINT pk_kb_article PRIMARY KEY (article_id)
);

CREATE TABLE KB_KEYWORD (
    keyword_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    keyword      VARCHAR2(100) NOT NULL,
    article_id   NUMBER NOT NULL,

    CONSTRAINT pk_keyword PRIMARY KEY (keyword_id),

    CONSTRAINT fk_keyword_article
        FOREIGN KEY (article_id)
        REFERENCES KNOWLEDGE_BASE_ARTICLE(article_id)
        ON DELETE CASCADE
);




