CREATE TABLE COMPANY (
    company_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    company_name    VARCHAR2(120) NOT NULL,
    status          VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at      DATE DEFAULT SYSDATE,

    CONSTRAINT pk_company PRIMARY KEY (company_id)
);

CREATE TABLE USER_ACCOUNT (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    company_id    NUMBER NOT NULL,
    name          VARCHAR2(120) NOT NULL,
    contact       VARCHAR2(120),
    role          VARCHAR2(50) NOT NULL,
    created_by    VARCHAR2(120),

    CONSTRAINT pk_user_account PRIMARY KEY (user_id),
    CONSTRAINT fk_user_company
        FOREIGN KEY (company_id)
        REFERENCES COMPANY(company_id)
);

CREATE TABLE PRIORITY (
    priority_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    level         VARCHAR2(50) NOT NULL,
    sort_order    NUMBER,

    CONSTRAINT pk_priority PRIMARY KEY (priority_id)
);

CREATE TABLE STATUS (
    status_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    status_name   VARCHAR2(50) NOT NULL UNIQUE,
    sort_order    NUMBER,

    CONSTRAINT pk_status PRIMARY KEY (status_id)
);

CREATE TABLE CATEGORY (
    category_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name   VARCHAR2(150) NOT NULL,
    sort_order      NUMBER,

    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE SUBCATEGORY (
    subcategory_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_id       NUMBER NOT NULL,
    subcategory_name  VARCHAR2(150) NOT NULL,

    CONSTRAINT pk_subcategory PRIMARY KEY (subcategory_id),

    CONSTRAINT fk_subcategory_category
        FOREIGN KEY (category_id)
        REFERENCES CATEGORY(category_id)
        ON DELETE CASCADE
);

CREATE TABLE TICKET (
    ticket_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    company_id      NUMBER NOT NULL,
    title           VARCHAR2(200) NOT NULL,
    status_id       NUMBER NOT NULL,
    created_date    DATE DEFAULT SYSDATE,
    created_by      NUMBER NOT NULL,
    assigned_to     NUMBER,
    priority_id     NUMBER NOT NULL,
    category_id     NUMBER NOT NULL,
    subcategory_id  NUMBER,
    subject         VARCHAR2(200),
    description     CLOB,
    sla_due         DATE,

    CONSTRAINT pk_ticket PRIMARY KEY (ticket_id),

    -- Foreign Keys
    CONSTRAINT fk_ticket_company
        FOREIGN KEY (company_id)
        REFERENCES COMPANY(company_id),

    CONSTRAINT fk_ticket_status
        FOREIGN KEY (status_id)
        REFERENCES STATUS(status_id),

    CONSTRAINT fk_ticket_priority
        FOREIGN KEY (priority_id)
        REFERENCES PRIORITY(priority_id),

    CONSTRAINT fk_ticket_category
        FOREIGN KEY (category_id)
        REFERENCES CATEGORY(category_id),

    CONSTRAINT fk_ticket_subcategory
        FOREIGN KEY (subcategory_id)
        REFERENCES SUBCATEGORY(subcategory_id),

    CONSTRAINT fk_ticket_created_by
        FOREIGN KEY (created_by)
        REFERENCES USER_ACCOUNT(user_id),

    CONSTRAINT fk_ticket_assigned_to
        FOREIGN KEY (assigned_to)
        REFERENCES USER_ACCOUNT(user_id)
);

CREATE TABLE TICKET_COMMENT (
    comment_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ticket_id     NUMBER NOT NULL,
    user_id       NUMBER NOT NULL,
    comment_text  CLOB,

    CONSTRAINT pk_ticket_comment PRIMARY KEY (comment_id),

    CONSTRAINT fk_comment_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES TICKET(ticket_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_comment_user
        FOREIGN KEY (user_id)
        REFERENCES USER_ACCOUNT(user_id)
);

CREATE TABLE TICKET_STATUS_HISTORY (
    ticketstatus_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    company_id        NUMBER NOT NULL,
    ticket_id         NUMBER NOT NULL,
    from_status_id    NUMBER,
    to_status_id      NUMBER NOT NULL,
    change_by         NUMBER NOT NULL,
    change_date       DATE DEFAULT SYSDATE,

    CONSTRAINT pk_ticket_status_history 
        PRIMARY KEY (ticketstatus_id),

    CONSTRAINT fk_history_company
        FOREIGN KEY (company_id)
        REFERENCES COMPANY(company_id),

    CONSTRAINT fk_history_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES TICKET(ticket_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_history_from_status
        FOREIGN KEY (from_status_id)
        REFERENCES STATUS(status_id),

    CONSTRAINT fk_history_to_status
        FOREIGN KEY (to_status_id)
        REFERENCES STATUS(status_id),

    CONSTRAINT fk_history_user
        FOREIGN KEY (change_by)
        REFERENCES USER_ACCOUNT(user_id)
);

CREATE TABLE KNOWLEDGE_BASE_ARTICLE (
    article_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    title         VARCHAR2(200) NOT NULL,
    content       CLOB NOT NULL,
    created_at    DATE DEFAULT SYSDATE,

    CONSTRAINT pk_kb_article PRIMARY KEY (article_id)
);

CREATE TABLE KB_KEYWORD (
    keyword_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    keyword      VARCHAR2(100) NOT NULL,
    article_id   NUMBER NOT NULL,

    CONSTRAINT pk_keyword PRIMARY KEY (keyword_id),

    CONSTRAINT fk_keyword_article
        FOREIGN KEY (article_id)
        REFERENCES KNOWLEDGE_BASE_ARTICLE(article_id)
        ON DELETE CASCADE
);




